### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by mightyiam** [remotemobprogramming/timer#27]
Please :dark_sunglasses: :sunglasses: :octopus: :shrimp:

**Comment by hollesse** [comment]
This would be a cool enhancement. We could therefore upgrade bootstrap to v5.3.0 this brings support for darkmode and we could then simply use the system settings of the user or even add a toogle to decide wether to use system settings or manually overwrite it.

**Comment by mightyiam** [comment]
Is it supposed to be in production?

**Comment by hollesse** [comment]
Not yet. We just changed the deployment of our dev instance from digital ocean to heroku. This will also happen on prod. At the moment my plan is to do this on Friday evening as we also have to change the DNS. If we do it on Friday evening the DNS caches have some time to get the new entries without much usage of the timer. But you can at least have a look at it on dev.timer.mob.sh ;)

**Comment by mightyiam** [comment]
Thank you for this! :pray:
