### ISSUE TITLE
White background flashes before dark one

### ISSUE THREAD

**Issue by mightyiam** [remotemobprogramming/timer#34]
Something I noticed and did not confirm or look into further.

Could be that if the stylesheet is loaded synchronously prior to the content, this would possibly be prevented.

**Comment by mightyiam** [comment]
In theory, JavaScript is not necessary. Can be purely CSS.

https://css-tricks.com/dark-modes-with-css/
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by mightyiam** [comment]
Then I would load that JavaScript synchronously in the HEAD element. According to what you're describing I would expect that to be the recommendation.

**Comment by hollesse** [comment]
You are right. I just looked at the source code of the bootstrap docs. There you can find the script in the head of the page. See line 17 [view-source:https://getbootstrap.com/docs/5.3/customize/color-modes/#sass-usage](view-source:https://getbootstrap.com/docs/5.3/customize/color-modes/#sass-usage)

**Comment by hollesse** [comment]
fixed in [d9bcf84](https://github.com/remotemobprogramming/timer/commit/d9bcf84f22655db0ce06b4d9462d5b26fead6092)
